# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 686)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_open = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_2.addWidget(self.btn_open)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_progress_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_progress_name.setObjectName("label_progress_name")
        self.horizontalLayout.addWidget(self.label_progress_name)
        self.label_progress = QtWidgets.QLabel(self.layoutWidget)
        self.label_progress.setObjectName("label_progress")
        self.horizontalLayout.addWidget(self.label_progress)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_progress_type = QtWidgets.QLabel(self.layoutWidget)
        self.label_progress_type.setObjectName("label_progress_type")
        self.horizontalLayout.addWidget(self.label_progress_type)
        self.edit_cls = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_cls.setObjectName("edit_cls")
        self.horizontalLayout.addWidget(self.edit_cls)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_previous = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_previous.setObjectName("btn_previous")
        self.horizontalLayout.addWidget(self.btn_previous)
        self.btn_next = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 20)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_open.setText(_translate("Form", "打开"))
        self.label_progress_name.setText(_translate("Form", "进度："))
        self.label_progress.setText(_translate("Form", "0/0"))
        self.label_progress_type.setText(_translate("Form", "类别："))
        self.edit_cls.setText(_translate("Form", "0"))
        self.btn_previous.setText(_translate("Form", "前一批"))
        self.btn_next.setText(_translate("Form", "下一批"))
